using Microsoft.EntityFrameworkCore;
using RateManager.Net10.Data;
using RateManager.Net10.Models;
using RateManager.Net10.ViewModels;

namespace RateManager.Net10.Services;

public class RateCalculationService : IRateCalculationService
{
    private readonly AppDbContext _db;
    private readonly IRateAuditService _audit;

    public RateCalculationService(AppDbContext db, IRateAuditService audit)
    {
        _db = db;
        _audit = audit;
    }

    public async Task<int> GenerateRatesAsync(GenerateRatesViewModel model, string? userName)
    {
        if (model.NumberOfDays <= 0)
        {
            throw new InvalidOperationException("Number of days must be greater than zero.");
        }

        var ratePlan = await _db.RatePlans.FirstOrDefaultAsync(x => x.RatePlanId == model.RatePlanId && x.IsActive);
        if (ratePlan == null)
        {
            throw new InvalidOperationException("Rate plan was not found.");
        }

        var selectedRooms = model.Rooms
            .Where(x => x.RoomTypeId > 0 && x.BaseRate > 0 && x.GuestCount > 0 && x.RoomCount > 0)
            .ToList();

        if (!selectedRooms.Any())
        {
            throw new InvalidOperationException("At least one room row is required.");
        }

        var configuredWeekendDays = await _db.WeekendDaySettings
            .Where(x => x.Enabled)
            .Select(x => x.Weekday)
            .ToListAsync();

        var endDate = model.StartDate.AddDays(model.NumberOfDays - 1);
        var batch = new RateGenerationBatch
        {
            RatePlanId = ratePlan.RatePlanId,
            SourceType = RateSourceType.Calculation,
            StartDate = model.StartDate,
            EndDate = endDate,
            NumberOfDays = model.NumberOfDays,
            GlobalAdjustmentPercent = model.GlobalAdjustmentPercent,
            WeekendAdjustmentPercent = model.WeekendAdjustmentPercent,
            Notes = model.Notes,
            CreatedBy = userName
        };

        _db.RateGenerationBatches.Add(batch);
        await _db.SaveChangesAsync();

        var rules = await _db.RateCalculationRules
            .Where(x => x.RatePlanId == model.RatePlanId && x.IsActive)
            .ToListAsync();

        foreach (var roomInput in selectedRooms)
        {
            var room = await _db.RoomTypes.FirstOrDefaultAsync(x => x.RoomTypeId == roomInput.RoomTypeId && x.IsActive);
            if (room == null)
            {
                continue;
            }

            for (var offset = 0; offset < model.NumberOfDays; offset++)
            {
                var date = model.StartDate.AddDays(offset);
                var dateTime = date.ToDateTime(TimeOnly.MinValue);
                var isWeekend = configuredWeekendDays.Contains(dateTime.DayOfWeek);
                var weekendPercent = isWeekend ? model.WeekendAdjustmentPercent : 0;
                var rulePercent = GetRulePercent(rules, room.RoomTypeId, date, dateTime.DayOfWeek);
                var totalPercent = model.GlobalAdjustmentPercent + roomInput.RoomAdjustmentPercent + weekendPercent + rulePercent;
                var calculated = CalculateRate(roomInput.BaseRate, totalPercent);

                _db.DailyRoomRates.Add(new DailyRoomRate
                {
                    RateGenerationBatchId = batch.RateGenerationBatchId,
                    RatePlanId = ratePlan.RatePlanId,
                    RoomTypeId = room.RoomTypeId,
                    RateDate = date,
                    DayName = dateTime.DayOfWeek.ToString(),
                    IsWeekend = isWeekend,
                    GuestCount = roomInput.GuestCount,
                    RoomCount = roomInput.RoomCount,
                    BaseRate = roomInput.BaseRate,
                    TotalAdjustmentPercent = totalPercent,
                    CalculatedRate = calculated,
                    FinalRate = calculated,
                    CalculationNote = BuildCalculationNote(model.GlobalAdjustmentPercent, roomInput.RoomAdjustmentPercent, weekendPercent, rulePercent),
                    CreatedBy = userName
                });
            }
        }

        await _db.SaveChangesAsync();
        await _audit.WriteAsync("RateGenerationBatch", batch.RateGenerationBatchId, "Create", null, null, "Generated by calculation", userName);

        return batch.RateGenerationBatchId;
    }

    public async Task UpdateManualRateAsync(ManualRateUpdateInput input, string? userName)
    {
        var rate = await _db.DailyRoomRates.FirstOrDefaultAsync(x => x.DailyRoomRateId == input.DailyRoomRateId);
        if (rate == null)
        {
            throw new InvalidOperationException("Daily rate was not found.");
        }

        var oldFinalRate = rate.FinalRate;
        var oldManualRate = rate.ManualRate;

        if (input.ManualRate.HasValue)
        {
            rate.ManualRate = Math.Round(input.ManualRate.Value, 3, MidpointRounding.AwayFromZero);
            rate.FinalRate = rate.ManualRate.Value;
            rate.IsManualOverride = true;
        }
        else
        {
            rate.ManualRate = null;
            rate.FinalRate = rate.CalculatedRate;
            rate.IsManualOverride = false;
        }

        rate.UpdatedAt = DateTime.UtcNow;
        rate.UpdatedBy = userName;

        _db.RateOverrides.Add(new RateOverride
        {
            DailyRoomRateId = rate.DailyRoomRateId,
            OldRate = oldFinalRate,
            NewRate = rate.FinalRate,
            Reason = input.Reason,
            CreatedBy = userName
        });

        await _audit.WriteAsync(
            "DailyRoomRate",
            rate.DailyRoomRateId,
            "Update",
            "ManualRate",
            oldManualRate?.ToString("0.###"),
            rate.ManualRate?.ToString("0.###"),
            userName);

        await _db.SaveChangesAsync();
    }

    private static decimal CalculateRate(decimal baseRate, decimal totalPercent)
    {
        var calculated = baseRate * (1 + totalPercent / 100m);
        return Math.Round(calculated, 3, MidpointRounding.AwayFromZero);
    }

    private static decimal GetRulePercent(IEnumerable<RateCalculationRule> rules, int roomTypeId, DateOnly date, DayOfWeek weekday)
    {
        decimal result = 0;
        foreach (var rule in rules)
        {
            if (rule.RuleScope == RateRuleScope.General)
            {
                result += rule.PercentageValue;
            }
            else if (rule.RuleScope == RateRuleScope.RoomType && rule.RoomTypeId == roomTypeId)
            {
                result += rule.PercentageValue;
            }
            else if (rule.RuleScope == RateRuleScope.Weekday && rule.Weekday == weekday)
            {
                result += rule.PercentageValue;
            }
            else if (rule.RuleScope == RateRuleScope.DateRange && rule.StartDate.HasValue && rule.EndDate.HasValue)
            {
                if (date >= rule.StartDate.Value && date <= rule.EndDate.Value)
                {
                    result += rule.PercentageValue;
                }
            }
        }

        return result;
    }

    private static string BuildCalculationNote(decimal globalPercent, decimal roomPercent, decimal weekendPercent, decimal rulePercent)
    {
        return $"Global {globalPercent:0.####}% + Room {roomPercent:0.####}% + Weekend {weekendPercent:0.####}% + Rules {rulePercent:0.####}%";
    }
}
